In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
mta = pd.read_excel('Significant_MTAs.xlsx', sheet_name='Significant MTA')
mta.head()

,Trait,Marker,Chr,Pos,Ref,Alt,df,F,p,-log10(p),chr:pos,Nearest gene,Nearest gene annotation (WheatIS),Candidate gene,Candidate gene description,Do we need a KASP-marker,Candidate gene reference (DOI),Reference article title
0,Awns,IAB09131,5A,698510016,T,C,2,657.84697,1.732500e-83,82.761327,chr5A:698510016,TraesCS5A02G542600,Hexose carrier protein HEX6,TraesCS5A02G542800,C2H2 zinc finger transcriptional repressor,Yes,10.1111/nph.16152,Sequence-based mapping identifies a candidate ...
1,Awns,IAB48252,5A,708290964,NaN,NaN,2,25.33744,2.016000e-10,9.695509,chr5A:708290964,TraesCS5A02G557200,Obtusifoliol 14-alpha demethylase,TraesCS5A02G542800,C2H2 zinc finger transcriptional repressor,-,10.1111/nph.16152,Sequence-based mapping identifies a candidate ...
2,Plant height,IAB60001,4B,30861562,NaN,NaN,1,22.77962,3.732600e-06,5.427989,chr4B:30861562,TraesCS4B02G043100,DELLA protein RHT-1,TraesCS4B02G043100,Rht-B1e,No,10.1104/pp.111.183657,Molecular Characterization of Rht-1 Dwarfing G...
3,Plant height,IAB07969,4D,18781242,NaN,NaN,1,24.28764,1.865900e-06,5.729112,chr4D:18781242,TraesCS4D02G040400,DELLA protein RHT-1,TraesCS4D02G040400,Rht-D1b,No,10.1104/pp.111.183657,Molecular Characterization of Rht-1 Dwarfing G...
4,Plant height,IAB57498,7B,407491560,NaN,NaN,2,18.69817,4.186300e-08,7.378170,chr7B:407491560,TraesCS7B02G397710LC,Uncharacterized,TraesCS7B02G055300,TaDHL-7B,Yes,10.3390/genes13060979,"ATP-dependent DNA helicase (TaDHL), a Novel Re..."

In [3]:
genotypes = pd.read_excel('Genotypes_filtered_imputed.xlsx', index_col='rs#')

In [4]:
genotypes_t = genotypes.transpose(copy=True)
genotypes_t.head()

rs#,IAB00012,IAB00017,IAB00031,IAB00041,IAB00062,IAB00085,IAB00113,IAB00129,IAB00133,IAB00151,...,IAB59691,IAB59696,IAB59697,IAB59733,IAB59734,IAB59763,IAB59860,IAB59908,IAB59987,IAB60001
alleles,C/T,T/C,A/G,A/G,C/T,G/T,A/G,C/A,A/T,A/C,...,G/C,C/T,C/G,A/G,C/T,A/T,A/G,T/C,C/G/T,A/T
chrom,1A,1A,1A,1A,1A,1A,1A,1A,1A,1A,...,UN,UN,UN,UN,UN,UN,UN,UN,UN,4B
pos,3776696,3847127,7643152,8295524,10068689,16434515,25791352,32476243,33374447,38729513,...,75460792,76409169,76763602,93835665,93835685,110692168,238397465,306757712,405155432,30861562
strand,+,+,+,+,+,+,+,+,+,+,...,+,+,+,+,+,+,+,+,+,+
assembly#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
significant_markers = mta['Marker'].unique().tolist()
significant_markers_table = genotypes_t[significant_markers]
significant_markers_table

rs#,IAB09131,IAB48252,IAB60001,IAB07969,IAB57498,IAB28956,IAB04062,IAB00955,IAB29579,IAB29292,IAB58331,IAB11647,IAB19354,IAB32845,IAB41988,IAB08754,IAB17595,IAB13554
alleles,C/T,C/T,A/T,G/T,C/T,C/T,C/T,C/A,G/C,T/G,T/C,G/T,G/T,A/G,C/T,C/T,G/T,T/C
chrom,5A,5A,4B,4D,7B,7B,2D,1B,7D,7D,7B,6B,2D,1B,3B,5A,2A,7B
pos,698510016,708290964,30861562,18781242,407491560,555163428,33957770,106765881,407713610,25190931,706119200,161342593,516926694,676812396,655860618,520117260,717188839,134556005
strand,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+
assembly#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Svarog,C,C,A,G,C,C,C,C,G,T,T,G,G,A,Y,C,G,T
06380AR83,C,T,A,G,C,C,C,C,G,T,C,G,G,A,C,C,G,T
Tandem,T,T,A,G,C,C,T,C,G,G,T,G,G,A,C,C,T,T
Laureat,C,C,A,G,C,C,C,C,G,T,T,G,G,A,C,C,G,T
Inea,C,C,A,G,C,C,C,C,G,T,T,G,G,A,C,C,G,T

In [82]:
df_out = pd.DataFrame()

for marker in significant_markers:
    alleles = significant_markers_table[marker]['alleles'].split('/')
    traits = [', '.join(mta.groupby('Marker', group_keys=True)['Trait'].apply(lambda x: x)[marker].to_list())]
    
    for allele in alleles:
        examples = significant_markers_table.groupby(marker, group_keys=True)[marker].apply(lambda x: x)[allele].index.to_list()
        column = pd.DataFrame({marker + '_' + allele: traits + examples})
        df_out = df_out.join(column, how='outer', sort=True)

df_out.head(10)

,IAB09131_C,IAB09131_T,IAB48252_C,IAB48252_T,IAB60001_A,IAB60001_T,IAB07969_G,IAB07969_T,IAB57498_C,IAB57498_T,...,IAB32845_A,IAB32845_G,IAB41988_C,IAB41988_T,IAB08754_C,IAB08754_T,IAB17595_G,IAB17595_T,IAB13554_T,IAB13554_C
0,Awns,Awns,Awns,Awns,Plant height,Plant height,Plant height,Plant height,Plant height,Plant height,...,Grain visual score,Grain visual score,Test weight,Test weight,Starch content,Starch content,Leaf rust,Leaf rust,Septoria blotch (flag leaf 2019),Septoria blotch (flag leaf 2019)
1,Tanais,Fenomen,Tanais,Eremeevna,Tanais,Esaul,Tanais,Fenomen,Tanais,Eremeevna,...,Tanais,Menestrel,Tanais,Krasnoobskaya_oz.,Tanais,Menestrel,Tanais,Yuka,Tanais,Menestrel
2,Menestrel,Ekspromt,Menestrel,Pamyat,Eremeevna,L.3124k4,Eremeevna,Aivina,Arsenal,Menestrel,...,Eremeevna,Viki,Eremeevna,Nemchinovskaya_57,Eremeevna,LYRIK,Eremeevna,Musik,Eremeevna,Fenomen
3,Arsenal,Esaul,Arsenal,Viki,Menestrel,L.3244k29-1,Menestrel,Viki,Aivina,Fenomen,...,Arsenal,NYCKOR,Menestrel,Bezostaya_100,Arsenal,Apache,Menestrel,Krasnoobskaya_oz.,Arsenal,LYRIK
4,Aivina,Donskaya_Yubileinaya,Fenomen,Musik,Arsenal,Nemchinovskaya_85,Arsenal,NYCKOR,Morozko,LYRIK,...,Fenomen,Nemchinovskaya_85,Arsenal,Deya,Fenomen,KWS_Barrel,Arsenal,Crimson,Aivina,Viki
5,Morozko,Nemchinovskaya_85,Aivina,Esaul,Fenomen,Mone,Morozko,Dmitrii,Vassa,Viki,...,Aivina,Turnia,Fenomen,Videya,Aivina,Euclide,Fenomen,L.2612k2-1,Morozko,NYCKOR
6,Vassa,Hadm_25612-02,Morozko,Olkhon,Aivina,7675h34-23,Vassa,Donskaya_Yubileinaya,Yuka,NYCKOR,...,Morozko,Dagmar,Aivina,Moskovskaya_40,Morozko,KWS_Zyatt,Aivina,Sila,Vassa,Musik
7,LYRIK,Moskovskaya_82,Vassa,Nemchinovskaya_85,Morozko,L.2612k2-1,LYRIK,Zimtra,Ekspromt,Musik,...,Vassa,Sineva,Morozko,NaN,Vassa,Clarion,Morozko,Novosibirskaya_32,Yuka,Apache
8,Yuka,Ordynka,LYRIK,Zimtra,Vassa,Cheget,Yuka,Hadm_25612-02,Bagrat,Nemchinovskaya_85,...,LYRIK,Bet_B_8_14,Vassa,NaN,Yuka,KWS_Siskin,Vassa,Zolotokolosa,Ekspromt,Turnia
9,Bagrat,Smuglyanka,Yuka,Etnos,LYRIK,Kalym,Ekspromt,KWS_Barrel,Pamyat,Apache,...,Yuka,Krasnoobskaya_oz.,LYRIK,NaN,Ekspromt,Caphorn,LYRIK,Altigo,Bagrat,Dagmar

In [83]:
df_out.to_excel('Example_cultivars.xlsx')