In [1]:
import pandas as pd

In [3]:
mta = pd.read_excel('Significant_MTAs.xlsx', sheet_name='Significant MTA')
mta.head(1)

,Trait,Marker,Chr,Pos,Ref,Alt,df,F,p,-log10(p),chr:pos,Nearest gene,Nearest gene annotation (WheatIS),Candidate gene,Candidate gene description,Do we need a KASP-marker,Candidate gene reference (DOI),Reference article title
0,Awns,IAB09131,5A,698510016,T,C,2,657.84697,1.732500e-83,82.761327,chr5A:698510016,TraesCS5A02G542600,Hexose carrier protein HEX6,TraesCS5A02G542800,C2H2 zinc finger transcriptional repressor,Yes,10.1111/nph.16152,Sequence-based mapping identifies a candidate ...

In [25]:
effects = pd.read_csv('MLM_effects.txt', sep='\t')
effects.head()

  Trait    Marker Locus     Site Allele   Effect  Obs
0  awns  IAB30003    1A  1211885      C  0.07667  172
1  awns  IAB30003    1A  1211885      T  0.01156   18
2  awns  IAB30003    1A  1211885      Y  0.00000    3
3  awns  IAB00012    1A  3776696      C  0.17107  171
4  awns  IAB00012    1A  3776696      T  0.04370   16

In [27]:
effects['Marker-trait'] = effects['Marker'] + effects['Trait']
effects.set_index('Marker-trait', inplace=True)
effects.head()

             Trait    Marker Locus     Site Allele   Effect  Obs
Marker-trait
IAB30003awns  awns  IAB30003    1A  1211885      C  0.07667  172
IAB30003awns  awns  IAB30003    1A  1211885      T  0.01156   18
IAB30003awns  awns  IAB30003    1A  1211885      Y  0.00000    3
IAB00012awns  awns  IAB00012    1A  3776696      C  0.17107  171
IAB00012awns  awns  IAB00012    1A  3776696      T  0.04370   16

In [32]:
dict = {'Awns': 'awns',
     'Plant height': 'plant_height',
     'Days to heading': 'days_to_heading',
     'Facultative habit': 'development',
     'Grain yield': 'grain_yield',
     '1000 kernel weight': '1000_kernel_weight',
     'Grain visual score': 'Grain_estimate_score',
     'Test weight': 'test_weight',
     'Starch content': 'starch_content_2019-2020',
     'Leaf rust': 'Leaf_rust',
     'Septoria blotch (flag leaf 2019)': 'septoria_blotch_leaf1_2019'}

output = pd.DataFrame(columns=effects.columns)
k = 0

for i in range(len(mta)):
    trait = mta.iloc[i]['Trait']
    trait_old = dict[trait]
    marker = mta.iloc[i]['Marker']
    output = pd.concat((output, effects.loc[marker+trait_old]), ignore_index=True)

output

,Trait,Marker,Locus,Site,Allele,Effect,Obs
0,awns,IAB09131,5A,698510016,C,-0.992540,144
1,awns,IAB09131,5A,698510016,T,-0.084865,39
2,awns,IAB09131,5A,698510016,Y,0.000000,10
3,awns,IAB48252,5A,708290964,C,-0.201010,115
4,awns,IAB48252,5A,708290964,T,0.227040,72
5,awns,IAB48252,5A,708290964,Y,0.000000,6
6,plant_height,IAB60001,4B,30861562,A,12.498540,175
7,plant_height,IAB60001,4B,30861562,T,0.000000,18
8,plant_height,IAB07969,4D,18781242,G,11.236870,164
9,plant_height,IAB07969,4D,18781242,T,0.000000,29
10,plant_height,IAB57498,7B,407491560,C,-25.904000,142
11,plant_height,IAB57498,7B,407491560,T,-24.770000,48
12,plant_height,IAB57498,7B,407491560,Y,0.000000,3
13,plant_height,IAB28956,7B,555163428,C,-33.394000,168
14,plant_height,IAB28956,7B,555163428,T,-34.534000,24
15,plant_height,IAB28956,7B,555163428,Y,0.000000,1
16,days_to_heading,IAB04062,2D,33957770,C,-1.253500,151
17,days_to_heading,IAB04062,2D,33957770,T,2.551300,40
18,days_to_heading,IAB04062,2D,33957770,Y,0.000000,2
19,days_to_heading,IAB00955,1B,106765881,A,-12.336000,24
20,days_to_heading,IAB00955,1B,106765881,C,-13.022000,168
21,days_to_heading,IAB00955,1B,106765881,M,0.000000,1
22,development,IAB29579,7D,407713610,C,0.131910,9
23,development,IAB29579,7D,407713610,G,-0.177300,183
24,development,IAB29579,7D,407713610,S,0.000000,1
25,development,IAB29292,7D,25190931,G,0.132540,10
26,development,IAB29292,7D,25190931,T,-0.016669,181
27,development,IAB29292,7D,25190931,K,0.000000,2
28,development,IAB58331,7B,706119200,C,-0.440940,49
29,development,IAB58331,7B,706119200,T,-0.445890,143
30,development,IAB58331,7B,706119200,Y,0.000000,1
31,development,IAB11647,6B,161342593,G,-0.118060,176
32,development,IAB11647,6B,161342593,T,0.028920,12
33,development,IAB11647,6B,161342593,K,0.000000,5
34,grain_yield,IAB04062,2D,33957770,C,-0.269470,151
35,grain_yield,IAB04062,2D,33957770,T,-1.293700,40
36,grain_yield,IAB04062,2D,33957770,Y,0.000000,2
37,1000_kernel_weight,IAB04062,2D,33957770,C,0.415390,151
38,1000_kernel_weight,IAB04062,2D,33957770,T,-3.383000,40
39,1000_kernel_weight,IAB04062,2D,33957770,Y,0.000000,2
40,Grain_estimate_score,IAB19354,2D,516926694,G,0.434270,157
41,Grain_estimate_score,IAB19354,2D,516926694,T,0.907140,26
42,Grain_estimate_score,IAB19354,2D,516926694,K,0.000000,10
43,Grain_estimate_score,IAB32845,1B,676812396,A,1.371240,161
44,Grain_estimate_score,IAB32845,1B,676812396,G,1.084030,20
45,Grain_estimate_score,IAB32845,1B,676812396,R,0.000000,12
46,test_weight,IAB41988,3B,655860618,C,2.063150,176
47,test_weight,IAB41988,3B,655860618,T,21.658570,6
48,test_weight,IAB41988,3B,655860618,Y,0.000000,11
49,starch_content_2019-2020,IAB08754,5A,520117260,C,2.761210,179
50,starch_content_2019-2020,IAB08754,5A,520117260,T,2.591890,10
51,starch_content_2019-2020,IAB08754,5A,520117260,Y,0.000000,4
52,Leaf_rust,IAB17595,2A,717188839,G,-9.021700,172
53,Leaf_rust,IAB17595,2A,717188839,T,14.440850,18
54,Leaf_rust,IAB17595,2A,717188839,K,0.000000,3
55,septoria_blotch_leaf1_2019,IAB13554,7B,134556005,C,-43.328000,39
56,septoria_blotch_leaf1_2019,IAB13554,7B,134556005,T,-42.119000,152
57,septoria_blotch_leaf1_2019,IAB13554,7B,134556005,Y,0.000000,2

In [33]:
output.to_excel('MTA_effects.xlsx')